
## Todos

## Notes

- board
  - go on board (lên xe lửa, máy bay)
  - across the board (diễn ra trên diện rộng)
- disagree = take issue with
- strike
  - the clock strikes twelve
  - strike the match
  - strike someone of the list
- grip
  - come to grips with the problem (tiếp cận, giải quyết vấn đề)
  - have a grip of sth (hiểu)
  - sb is gripped by sth (bị xúc động vì thứ gì đó)
  - in the grips of sth (đang trải nghiệm cái gì đó unpleasant)
- Khác nhau giữa suspect and doubt
  - suspect: nghi ngờ điều gì đó đúng
  - doubt: nghi ngờ điều gì đó sai (nghĩ rằng nó sai)
