## Todos

- [x] Writing vocabulary: add vocabulary for 2 topics: Environment and History
  - [x] Environment
  - [x] History
- [x] Writing: Write 2 passages for writing part 2
  - [x] Environment
  - [x] History

## Notes

  - divert / allocate / allot sth to sth: chi tiền cho...
  - in relentless pursuit of economic growth: chạy theo tăng trưởng kinh tế
  - on the increase: tăng trưởng
  - a lot of - synonym
    - a host of
    - innumerable ammount
  - large - synonym
    - colossal
  - seriously lacking - synonym
    - woefully / grossly inadequate
  - là cơ sở của một xã hội ổn định
    - form a **backbone** of a **functioning society**
  - là một thành phần không thể thiếu
    - is integral to ...
    - Historical buildings, monuments, and traditions are integral to a country's cultural identity and collective memory.
  - không thể thay thế
    - irreplaeable
  - đoàn kết dân tộc
    - social cohesion and people's sense of belonging
  - tạo ra lợi thế về kinh tế
    - generate tangible economic benefits
  - tạo cơ hội việc làm và doanh thu về thuế
    - create employment and produce tax revenue
  - vì thế cho nên - because of this
    - in this sense
  - bảo vệ di sản văn hóa
    - safeguarding places of historical significant
