## Done

## Notes

  - Part 1
    - Education background?
      -
    - What's your favorite subject?
    - Do you think education matters more for young people rather then elderly people?
      - regardless of age
      - it takes more informal forms such as reading books, watching informative videos, or staying updates with the news
    - Tips
      - Vary vocabulary
      - Use multiple structures
      - Example
        - furnish a solid foundation of credible and well-structured knowledge
        - maintain cognitive agility and adapt to technological advancement
  - Part 2
    - How technology has changed education?
      1. interactive
      2. more source of information ->  provide students with more ways to acquire knowledge + enhance social inclusivity
      - fix:
        - revolutionize educational paradigm / education methodologies
      - immersive and participatory learning experience
    - How technology will change education in the future?
      1. interactive: hands-on education modality
      2. global learning experience
        - break down geographical barrier provide high-quality education experience for everyone
        - encourage cultural exchange -> gain diverse perspectives + broaden understanding of the world
        - access lectures and resources from leading experts -> bridge the gap between remote areas and top-tier universities
    - How AI change the landscape of model education? Advantages and Disadvantages
      - AI facililtates personalized learning pathways
    - Parental involvement?
      - Reasons
        - Parents significantly influence children academically
          - Supportive, involved parents often
          - Example: Parents set a reading habbits -> vocabulary, comprehension, and confidence
        - Identify challenge early -> prevent small issues from becoming bigger gaps
        -
      - Approaches
    - How to make education more accessible for disabled students?
      -
      - 1-on-1 meeting -> provide a safe space to openly share challenges, ensuring their needs are understood and addressed early
      - encourage peer mentoring -> more actionable solutions -> the better the answer
      - fix
        - lengthy -> plan: idea + example (+ conclusion)
    - Writing tips
      -
