
## Photo capturing of Building

1. mặt tiền + mặt kính + chụp từ dưới lên
  - I sometimes capture **architectural details**, especially the **façade** and the **glass exterior**. Taking photos **from a low angle**-shooting from the bottom up-also gives a really interesting and dramatic perspective.

## Describe a building

### Overall architecture, meaning, surrounding

1. gần đó nhưng không phải nearby
  - The area around the building is really convenient-there’s a park, a supermarket, and several cafés **within walking distance**. My friends and I often go there for a relaxed stroll or to **grab a bubble tea**, although we haven’t actually been inside the building itself yet.
2. lấy cảm hứng từ khóm tre Việt Nam -> thường được biết đến như là
  - What I love about it is that the design is inspired by a **cluster of Vietnamese bamboo**, and it’s **widely regarded as** the tallest building in Vietnam.
3. nhà cao tầng mọc lên -> thay đổi diện mạo thành phố
  - A lot of **high-rises** have **gone up** recently, and they’ve really **changed the city’s skyline**.

### Scene from above

1. ngắm nhìn từ phòng observation
  - If I got the chance, I’d love to go there and **take in the views from the observation deck**.
2. cảnh choáng ngợp
  - I've heard that the view from there is breath-taking and awe-inspiring

### Flaws

## Do you want to live in a tall Building?

1. chung cư cao tầng
  - I could live in a **residential tower** for the **convenience**, but I’d miss the **privacy** and **sense of community**.
  - Those apartment blocks also has **on-site facilities** (gyms, pools,...) and better **securities**. They also end to be in the city center so they are close to public transport.
  - That said, the elevator requires **long waiting time**. And often, it feels **impersonal** because you don't really know your neighbors.
