
## Crime

- longer prison sentence -> extending imprisonment
- prison punishment -> imprison someone
- criminal
  - potential / would-be criminal
  - offender
- punishment
  - deterrent
  - sentence
- crime
  - criminal activity
- phán quyết của tòa án
  - The jury has reached a **verdict**.
  - The judge **hand down** a sentence
- tội phạm có tổ chức
  - organized crime - terrorism, drug/people trafficking
- tội phạm tài chính / công nghệ (không bạo lực)
  - white-collar criminal
- break the law -> synonym
  - breach the law
- careless behaviors that cause serious harm or death
  - criminal negligence
- khai thác lỗ hổng luật phát để trục lợi
  - Some multi-national corporations **exploit legal loopholes** to **minimize their tax obligation**, thereby **deprive** the government of tax revenue to necessitate public service. For example, some companies **shift profit** to **offshore subsidiaries** (company possessed by a larger company) in **tax havens** (places with low or zero tax rates), even though their primary business takes place elsewhere.
    - offshore: locate in another country
- hầu tòa
  - Public officials who engage in corruption should **stand trial**, regardless of their political status or social influence.
- thú nhận phạm tội / chối tội
  - In many cases of **financial misconduct**, executives **plead guilty to lesser charges** to avoid **lengthy prison sentences**.

## Punishment

- giải pháp trừng phạt hiệu quả
  - Longer prison sentences often **act/serve as a strong deterrent** to would-be offenders.
- đối diện với việc ở tù nhiều năm
  - If potential criminals know that they may ..., they will think twice before committing offences.
- nghien thuoc
  - Certain factors such as poverty, lack of education, or **drug/substance abuse** should be considered when determining a sentence for a crime.
- chuong trinh cai tao
  - rehabilitation program
- dao tao nghe nghiep
  - vocational training
- giao duc trong nha tu
  - education in prison
- phuong phap ngan chan
  - prevention strategies
- chuong trinh ho tro nguoi tre
  - youth support programmes
- huong giai quyet giam xung dot
  - deescalation approach
- tang vai tro cua canh sat / giam sat
  - improved policing
- phạt nặng / nhẹ
  - harsh / lenient punishment

## Criminal behaviors

- commit a crime
  - commit an offence
  - commit offences
- tai hoa nhap xa hoi
  - reintegrate into society
- song dung voi phap luat
  - earn a lawful living
- tai pham
  - reoffend
  - repeat offence
- lanh an
  - to serve a sentence
- an tu -> gianh quyen nuoi con
  - custodial sentence -> get a custody

## Verdict

- tôn trọng các quy tắc của luật pháp
  - Judges are expected to **uphold the law** impartially.
- sai phạm trong tố tụng / xét xử
  - a miscarriage of justic

## Public response

- phan no cua xa hoi
  - public outrage
