
1. sự thải các khí có hại
  - The **emission of harmful gases** has a disastrous effect on citizens's health.
2. tài nguyên có hạn, không
  - The excessive use of private vehicles causes depletion of **finite and non-renewable resources**.
3. ben vung doi voi moi truong
  - Those providing immediate benefits, this approach is not **environmentally sustainable**.
4. bãi rác
  - **Overreliance** on landfill is **inherently unsustainable** because it is a finite disposal method that **squanders recoverable resources**, generates **methane emissions**, and creates **long-term contamination risks** through **leachate**.
5. the curb of greenhouse gases
6. o nghiem nguon nuoc
  - contaminate the river
7. tay trang trong viec bao ve moi truong
  - Consumers are increasingly sceptical of **corporate greenwashing**. Stricter report rules can mitigate such issue.

## Endangered Species

1. bên bờ vựng tuyệt chủng
  - Because of human's relentless pursuit of economic growth, some wild species are **on the brink of extinction**.
2. poaching and illegal wildlife trading
3. loss of habitats

## Human Intervention

1. reintroduce species into the wild
2. nhan giong trong moi truong nuoi nhot
  - **Captive-breeding programmes** are not only a solution to **rebuild population of rare species**, but can also be used to **educate the public**.
3. reduce carbon footprint
4. shift to renewables

## Policies

1. implement stringent policy
  - Governments can **implement stringent regulations** by first **capping** the use and discharge of hazardous chemicals along production lines and requiring firms to **document and track** waste from source to final treatment. **Non-compliance** should trigger meaningful sanctions-**hefty fines**, **suspension of operating permits**, or even **temporary shutdowns**-so that breaking the rules costs more than following them. Under the **polluter-pays principle**, companies should also be obliged to **fund remediation** and cover the **safe treatment and disposal** of dangerous waste rather than dumping it illegally. Finally, **transparency** is crucial: mandating **public disclosure** of emissions and waste data enables communities and the media to **scrutinise** offenders, increasing the likelihood of detection and swift enforcement.
