
## Diet and Eating Habits

1. eating the right mix of different kinds of foods
  - I try to follow a **balanced diet**, but during busy weeks I eat out more than I should.
2. food that contains many nutrients for its size
  - Home-cooked meals are usually more **nutritionally dense** than fast food.
3. food that is produced in factory with many **addictives**
  - I’m trying to cut down on **ultra-processed food** like **packaged snacks** and **instant meals**.
4. food that is cooked at home
  - home-cooked/home-prepared meals
5. how someone usually eat (chế độ ăn uống)
  - People's **dietary habits** have changed a lot because of the busy lifestyles.
  - Many young people have **irregular eating patterns**, especially those who work late.
6. ăn ngoài
  - Home-made food is more cost-effective than **eating out** daily.

## Describe a dish

### 1. A dish you like

1. have unique taste
  - The dish has a **distinctive flavor** that I'd never tried before, which is really memorable.
2. food with the right amount of **spices**
  - The food is very well-seasoned, every taste is balanced and enjoyable.
3. the food that makes you feel relaxed and comfortable
  - Whenever I feel stressed, I usually turn to my **comfort food** which is soup or noodles.
4. the food that you initially didn't like but later enjoyed
  - Seafood is kind of an **acquired taste** for me. I couldn’t enjoy it at first, but suddenly everything just clicked, and now I think it’s not only **distinctive in flavour** but also **nutritionally dense**.
  - Spicy food is kind of an **acquired taste** for me, I couldn't enjoy it at first, but suddenly everything just clicked and now I appreciate its **distinctive aftertaste**.
5. looked or smelled delicious
  - The street food smelled **mouth-watering**, I couldn't resist trying it.

### 2. A dish you hate

1. too strong **in taste**
  - The sauce was a little **overpowering**, which made the dish **less appealing** **after the first bite**.

## Describe the process of making a dish

### 1. Preparation

1. prepare the ingredient
  - We **source the ingredients** from the local market to make sure they are fresh.
2. soak food in sauce or spices
  - The meat is **marinated** overnight to absorb the flavors.
3. cut into small / large pieces
  - finely chopped / roughly chopped
4. leave food for a short time before cooking
  - leave it rest

### 2. Cook

1. control heating temperature
  - heat sth over low/medium/high flame
2. mix often / sometimes
  - stir constantly / occasionally
3. heat until bubbling
  - bring sth to a boit / sth comes to a boil
  - When the water **comes to a boil**, put the noodles in.
4. cook until it turn yellow/brown
  - The onions are cooked until **golden brown**
5. cook slowly just below boiling
  - The soup is **left to simmer** for one hour.
6. cook quickly with high heat to lock in flavor
  - The meat is **seared** to keep it juicy

### 3. Flavoring

1. Finally, the dish is **seasoned to taste**.
2. Fresh herbs are added to **enhance the flavour**.
3. A bit of sugar helps **balance the flavours**.

### 4. Finishing and Serving

1. Once it’s ready, the dish is carefully **plated**.
2. It’s **garnished** with fresh herbs before serving.
3. The dish should be **served immediately**.
4. After that, the meal is **ready to be enjoyed**.

### 5. Comments on the Process

1. Making this dish is a **time-consuming process**, but it’s worth it.
2. Traditional food preparation can be quite **labour-intensive**.
3. The food is **handmade rather than mass-produced**.

### 6. Industrial Food Production

1. same method is used every time
  - Industrial food relies on **standardized process**.
2. is checked for quality and consistency
  - Strict **quality control** is essential for a food company to gain trust from its customers.

## Health issues related to Eating Habits

1. long-term health consequences
2. paying attention on what and how you eat
  - conscious eating
3. obesity rates
  - **Obesity rates** increase because young people rely too much on fast food.
4. health problem caused by poor eating habits
  - Poor diets can lead to serious **diet-related illnesses** like diabetes.
5. not eating too much of something
  - I think it’s fine to eat fast food occasionally, as long as it’s in **moderation**.
6. understanding which food is healthy
  - There’s more **nutritional awareness** nowadays, especially among young people.

## Cultural Aspect

1. culinary tradition (aspects of tradition that are related to food) > traditional dish
2. cultural identity
  - Culinary tradition is among important things that shape our **cultural identity**
3. The recipes are **passed down through generations**.
4. Cooking and eating together encourage **family bonding**.
5. Local food festivals create a **strong sense of community**.

## Modern Life

1. Fast food offers **instant gratification**, but eventually leads to health issues.
2. mass-produced meals
3. convenience-driven lifestyle
4. time-pressed individual
