
## The past

1. thời kì đã qua
  - bygone era
2. sự liên tục trong văn hóa
  - Storytelling, especially folklore, is a mean to maintain **cultural continuity** via passing teachings and practices from the past.
3. danh tính về văn hóa + ký ức tập thể (hiểu biết chung của người dân về những gì trong quá khứ)
  - Preserving cultural heritage like historical sites, monuments, and traditions is preserving a country's **cultural identity** and **collective memory** of its people.
4. thời điểm quan trọng trong lịch sử
  - The invention of the printing press is a **turning point in history** because it makes knowledge accessible to **the masses**.
5. di sản lịch sử
  - Colonialism has left a complex **historical legacy** that still shapes political relations today.
6. chứng kiến (lịch sử)
  - Ancient ruins **bear witness to** the advanced engineering skills of early civilizations.
7. di sản văn hóa phi vật thể
  - intangible cultural heritage like languages, rituals or **folklore**. (không số nhiều)
8. nguồn gốc tổ tiên
  - Many people research their **ancestral roots** to better understand who they are.

## Human impact

### Postive

1. bảo tồn truyền thống
  - safeguard traditions
2. bảo tồn di sản
  - preservation of historical sites
  - heritage conservation
3. truyền từ đời này sang đời khác
  - passed down through generations

 4. hòa tan các giá trị văn hóa
   - With the development of tourism, native people should do their best to keep their cultural values from being diluted.
 5. các vấn đề trong nước
   - current affairs in one's country
   - domestic current affairs
   - national / domestic issues

### Negative

1. cultural erosion
  - Global media has accelerated **cultural erosion** in smaller communities. For example, children in many rural communities engage with international content (Youtube, Netflix) more than **local media**. As a result, they often speak English more fluent than their **native dialects**, or don't keen on preserving their community's cultural practices, which leads to the disappearance of **indigenous languages**.
2. con dao 2 lưỡi
  - Tourism is a **double-edged sword**: it funds conservation but can also damage heritage sites.
3. thương mại hóa văn hóa
  - The **commercialisation of culture** can make traditional festivals feel artificial.
