
1. kênh tin tức (Vox, The Atlantic, The Guardian...)
  - Some **news outlets** may have political bias.

## Media

1. được đưa tin rộng khắp
  - The event receive a **widespread media coverage**.
2. nhắm đến đối tượng...
  - Romantic TV series often target at teenagers and people at 18-24, who have a vibrant social life but still maintain a carefree, dreamy outlook on life and the future.
  - tệp khán giả -> target audience

## News

1. khắc hoạ một cách thiên vị
  - Achievements of certain political parties are **portrayed / featured in a favorable highlight**, while those from others are suppressed or omitted entirely.
2. suppression of information
  - In some country, media **censorship** is very strict.

## Advertising

1. products shown in movies / viral videos
  - **Product placement** is common in Hollywood films.
2. kỹ thuật thuyết phục -> ảnh hưởng hành vi người dùng
  - Advertisements usually use **persuasive techniques** to profoundly influence **consumer behavior**.
3. promotion from famous figures
  - Celebrity **endorsements** increase sales dramatically.
4. thu hút về phần nhìn
  - The billboard was extremely **eye-catching**.
5. overstatements
  - Certain cosmetic advertisements are misleading, as they imply that their products contain mainly natural ingredients by incorporating natural imagery and scenic backgrounds into their marketing campaigns.
6. give false impression
  - Advertisements are often **misleading** in the sense that they **portray an idealized lifestyle** and imply that consumers can attain it by solely through purchasing a particular product.
