
## Appearance

### 1. Beautiful

1. clean, tidy and well-dressed (chải chuốt, chăm chút vẻ bề ngoài)
  - He's a **well-groomed** men, always appeared tidy and neatly-dressed.
2. có dáng người cân đối, cường tráng vì tập thể hình nhiều
  - He has a **well-built** body since he works out regularly.
3. gò má cao
  - Her **high cheekbones** give her an elegant and ambitious look.
4. Khuôn mặt có đường nét rõ ràng -> gây ấn tượng mạnh khi nhìn
  - He has **defined facial features**, which make him **striking** to look at.
5. có phong thái tự tin
  - He has **confident posture**, which creates a good first impression.
6. gầy
  - She's **slender**, like a model.
7. thân hình khỏe khoắn
  - He looks **lean** since he has a healthy diet and exercise regularly.
8. tóc ngang vai, uống lọn nhỏ
  - She has **shoulder-length, tightly curled hair**.
9. đẹp lão
  - The old woman **ages gracefully**, she still looks very elegant.
10. có phong thái
  - He **carries himself pretty well**, which gain initial trust from people working with him.
11. know which clothes fit your body and the situation
  - He has a good **sense of style** without following trends.

### 2. Ugly

1. tóc hói
  - His stressful years in the academic environment left him with a **receding hairline**.

## Personality

### 1. Good

1. willing to consider new ideas
  - She’s very **open-minded**, so it’s easy to discuss different opinions with her.
2. calm and sensible in difficult situations
  - He’s quite **level-headed**, especially when dealing with stress.
3. able to recover quickly from difficulties
  - She’s incredibly **resilient**, even after facing several setbacks.
4. able to control one’s behavior
  - He’s very **self-disciplined**, which helps him easily achieve all his tasks.

### 2. Bad

1. khiêm tốn, nền nã
  - He has an **unassuming** appearance, so people often underestimate him.

## Intelligence

1. nhạy bén, ứng biến nhanh
  - She’s very **quick-witted**, which makes conversations with her enjoyable.
2. have deep meaning
  - He made an **insightful** comment about human behavior.
3. be able to find different ways to solve one's problem
  - She’s very **resourceful** and can solve problems creatively.
4. có năng lực
  - He’s **highly competent** and trusted with important responsibilities.

## Behavior

1. easy to talk to
  - She’s very **approachable**, so people feel comfortable asking for help.
2. practical and realistic -> make people feel relatable
  - Despite his success, he’s very **down-to-earth**.
3. just think of yourself
  - She's a **self-centered** person, she thinks of everything in terms of her benefits and ignore everyone else.
4. determined and firm
  - She’s **strong-willed**, which helps her achieve her goals.

## Relationship

1. helpful and encouraging
  - My family has always been very **supportive**.
2. can be relied on
  - He’s extremely **trustworthy**, which is rare these days.
3. skilled at interacting with others
  - He’s **socially adept**, so he fits into new environments easily.
4. keep strong personal connections
  - It’s difficult to **maintain meaningful relationships** in a busy lifestyle.

## Morale and Sense of Ethics

1. có sự nhất quán trong hành động và lời nói
  - He makes decisions and behaves with **integrity**, that's why people tend to counted on him.

## Influence and Impact

1. be a person that someone look up to
  - My parents are **role models** to me
2. có ảnh hưởng tốt
  - Parents can **have a positive influence on** their children’s behaviour.
3. để lại ấn tượng tốt
  - He **left a lasting impression** on everyone he worked with.

## Negative traits

1. doesn't show emotions
  - He seems **emotionally distant**, even with close friends.
2. cannot be relied on
  - It’s frustrating to work with someone who’s **unreliable**
