
## Overall plan

## Self-study time

- Time: 2 weeks (17/01 to 31/01)
- Work to do
  - Review grammar, how to construct a complex sentence
  - Learn vocabulary from a wide range of topics (from concrete topics like food, personal hygiene, health, to abstract ones like crime, politics, or the environment)
  - Tips and tricks for each part
- Everyday plan (3h)
  - (2h) Study each topic for 40 minutes, including (3x14 = 42 topics)
    - Vocabulary / idiomatic phrases + How to construct a sentence using that vocabulary
  - (1h) Review vocabulary of older topics randomly

## Study with mentor

- Time: 1 month (01/02 to 28/02)
- Work to do
  - Focus on improving Speaking and Writing
  - Do mock tests -> Reflect and improve flaws
- Everyday plan (3h)
  - (3h when there are no classes) Pair 2 skills together
    - Reading + Speaking
    - Listening + Writing
  - (3h when there are classes) Follow the instruction (or watch live streams)
    - Writing: Huy Forum

## Final Revision Week

- Time: 1 week (01/03 to 07/03)
- Work to do
  - Review all learning points
  - Do forecasting tests
- Everyday plan (3h)
  - (3h) Do these things interleavingly
    - Taking test (L+R+W) at once to get familiar with the real exam
    - IELTS speaking forecasts
    - Review past learning points, vocabulary and grammar

## Daily plan

## Time spent for each test

- Listening
  - Take test: 30 min
  - Review (re-listen with transcript for difficult parts): 30 min
- Reading
  - Take test: 60 min
  - Review (check for errors + learn difficult vocabularies): 30 min
- Speaking
  - Take test: 15 min
  - Review (refine the idea + learn necessary vocabulary + develop strategy for speaking): 1 hour
- Writing
  - Take test: 1 hour
  - Review (fix vocabulary, grammar + enrich the passage + develop strategy for writing): 1 hour

## Goal

Reading 9.0, Listening 9.0, Speaking 7.5, Writing 7.5
