
## Reading Habits

1. dành ra thời gian (dù rất bận rộn)
  - I try to **carve out time for** reading before bed, even if it’s only fifteen minutes.
2. là một nhiều đọc nhiều
  - I used to be an **avid reader**, but my coursework and workload has slowed me down recently
3. đọc lưa thưa, không thường xuyên
  - During the exam season I would **read sporadically**, mainly on the weekends.
4. đọc một chút vào mỗi thời điểm (dip into a book)
  - I often **dip into short story collection** when I'm commuting.
5. đọc một lần rất lâu
  - If the plot is **gripping**, I will **binge-read** the book for **hours without noticing the time**.
6. mở mang tầm nhìn
  - Even when a book isn’t great, reading it can still **broaden my horizons** and **make me consider possibilities I wouldn’t have thought of otherwise**.

## Books

### General Description

1. sự trốn thoát
  - For me, fantasy novels are pure **escapism** after a tiring day.
2. kích thích về mặt trí tuệ
  - Non-fiction are intellectually stimulating, especially books on philosophy or psychology.
3. chìm đắm vào
  - I get so **engrossed in** thrillers that I **lose track of time**.
4. strongly interested/excited
  - I was **gripped by** the opening chapter-it **set the tone** perfectly.
5. khiến tôi đồng cảm
  - The characters' struggles and psychological development really **resonate with** me.

### Content

1. thách thức quan điểm cho rằng
  - Some books **challenge the narrative that** success is purely about talent.
2. supported by strong evidence
  - The book is opinion and story-based, which makes it not **well-substantiated**.
3. express clearly + tường minh
  - The author is very **eloquent** in presenting his arguments and viewpoints, and his explanations are especially **lucid** when **tackling difficult topics**.

### Impacts

1. nặng về cảm xúc
  - The memoir was **hard-hitting**, especially the parts about poverty.
2. gợi nhiều suy nghĩ, self-reflect
  - I like **thought-provoking** books about the psychology of our everyday choices and behaviors.
3. cuốn -> lật trang liên tục
  - That novel is a **page-turner** - I finish reading it in 2 days.

## Reading Techniques

1. đọc lướt
  - I'm fairly **selective about what I read**, I usually **skim and scan** the books for main ideas and keywords, then decide to read it if I find the content exciting.
2. suy ý nghĩa từ bối cảnh (khi không biết nghĩa một từ)
  - During my childhood, I read hard foreign novels by **inferring** the meaning of some complex words from its context
3. giải mã (một văn bản khó hiểu, rối rắm)
  - Some academic papers are hard to **decipher** without sufficient background knowledge. And sometimes you have to **grapple with** the author's dense and unique writing styles.
4. đọc một cách có phê phán -> phát hiện ra thiên vị / thiên kiến -> suy xét các luận điểm, luận cứ cẩn trọng
  - For some knowledge- and argument- dense books, I have to spend much time to **read critically**, vigilantly **detect biases** and **weigh up arguments** instead of reacting emotionally.

## Stories

## Opinion

1. con dao hai lưỡi
  - E-book is a **double-edged sword** - on one hand, it's convenient and more economical, but on the other, it's easier for you to get distracted and is not good for your eyes.
2. especially like something
  - I **have a soft spot for** literature, a good literature book always resonates with my soul.
3. bị cuốn bởi
  - I'm **drawn to** non-fiction books discussing topics related to philosophy or psychology.
