
- advancement / emergence of artificial intelligence
  - AI-driven changes

## Impact

- boost productivity
- replace manual labor
- drive economic growth

## Human-possessed skill set

- jobs that require advanced expertise or analytical thinking
  - While **manual jobs** declines, knowledge-intensive roles **are likely to** expand.
- công việc mang tính sáng tạo, không mang tính đều đặn
  - AI struggles to replicate **creative and non-routine work**, such as artistic expression or strategic planning.

## Skill set that can be replaced by technology

- mental tasks that follow fixed rules and patterns
  - Artificial intelligence is particularly effective at automating **routine cognitive tasks** such as **data entry** and **basic analysis**.

## Labour market

- job losses -> job displacement
- clerical work -> data entry or basic analysis
- phân cực lao động
  - Technological advancement **accelerates** **labour market polarization / employment polarization**. For example, **manufacturing** or **administrative** jobs (data entry, document filling, phone answering,...) face **technological redundancy** while there is a high demand for low-skill jobs (waiter, caretaker, pet sitter,...) and high-skill jobs (engineer, doctor, university lecturer,...)
- the number of new jobs created outnumbered the number of job losses
  - Despite initial job losses, technological development often results in **net job creation** in the long term.
- reskilling and upskilling
  - Governments and institutions should invest in **reskilling and upskilling programmes** to **equip workers with the professional and collaborative skills** required in an AI-driven economy.

## Policy and Best Practices

- sự giám sát về mặt đạo đức
  - When artificial intelligence is used in recruitment, human **ethical oversight** is necessary to ensure that algorithms do not **discriminate against** candidates based on gender, ethnicity, or age.
- kết hợp giữa người và máy
  - The future of work is likely to depend on **human-machine collaboration**, rather than **full automation**
- kỹ năng k còn phù hợp nữa
  - A major challenge caused by automation is the growing **skill mismatch** in the workforce.
- phát triển khả năng con người (thay vì thay thế)
  - Intelligent machines are likely to augment human capabilities rather than fully replace it.
