
## Opening

1. tôi không có nhiều kiến thức về ...
  - I’m not particularly well-versed in…
  - This topic is not something I've looked into in depth, but...
2. not updated on the topic
  - I’m not fully up to speed on
3. nêu preference đối với một thứ mình không tìm hiểu nhiều
  - I don’t have strong views on that, since I haven’t read much about it.

## Not sure

1. Theo như tôi biết
  - As far as I know…
  - From what I've gathered...
  - I could be wrong, but…

## Buying time

1. That’s an interesting one-let me think for a second.
2. Off the top of my head…

## What to say when don't know what to say

1. General view
2. Compare with related topics
3. Talk about pros and cons
4. Your own experience
