
1. Remember to prepare on difficult topics instead of topics that you feel confident with (ielts-advantage)
2. Try to ace Part 3 speaking to get a higher band (7 - 9)
  - `It’s not something I’ve given much thought to, but I’d say that...`
3. Try to use topic-related vocabulary rather than C2-level words in a forceful manner
4. Làm thế nào để 9.0 vocab (tung-dang)
  - paraphrasing
    - nhớ paraphrase đầu câu hỏi
      - like -> be big on sth, be my cup of tea, detest
    - (optional) xuyên suốt câu hỏi
  - idiomatic expression
  - less common vocabularies
    - use [Less common vocabularies](less-common-vocabularies) for words that exist frequently in the speaking test
      - important
      - more popular
      - in my opinion
      - each option has pros and cons
      - like
      - don't like
5. Expand ideas in speaking
  - Give examples
    - One of my perennial favorite is...
  - Talk about its benefits
    - Physical
      - keep fit / get lean / stay in shape
    - Mental
      - let my hair down / blow of some steam
  - Popularity
    - For the most part, ... big on ...
    - ubiquitous / be all the rage
  - Make it personal
    - Your taste/preferences
      - I'm an avid reader / swimmer
      - I'm pretty ... - conscious
      - I can't dance / cook to save my life
    - Past experiences
      - Back in the day
  - Admit your flaws
    - Admit you don't know much about the topic
      - I don't know the first thing about ... / I am clueless about ...
    - Embarrassing things
  - Connect with previous answers
    - As I was saying, as I mentioned
    - So remember I was telling you about the fact that ...
  - Compare with the norm
    - This is quite peculiar / This may sound bizarre
    - ... which I guess is the norm in ...
    - This is not the case with ... (những cái khác thì không như vậy)
    - There's a common misconception that ...
    - Unlike / compared to
6. Speaking formula
  - Introduce (what / where / who)
  - Describe
  - Impact (why it matters)
  - Conclusion (overall feeling and evaluation)
