
1. Describe a gift that you receive as a child (or are not electronic devices).
2. Describe a memorable toy of yours.
3. Something that help you learn
  One present that **left a strong impression** on me was a **LEGO construction set** I received when I was about 7 years old. It was a birthday gift from my parent. And I remember being **genuinely thrilled** when I opened it.
   The toy itself is a set of **well-crafted colorful plastic blocks** that could be connected in countless ways. What made it special is that it wasn't just **visually engaging**, but also **highly versatile**, in the sense that you can build various kinds of construction just from some basic, foundational blocks. I built some simple houses at first, and then **moved on to** more complex structures like bridges or vehicles. The pieces are **lightweight yet durable**. They remained undamaged despite my several attempts to **take the blocks apart and put them together**.
   **In hindsight**, what I appreciate most about this gift is that it encouraged **imaginative and independent play**. I could spend hours building things on my own, which really helped me develop patience and basic **problem solving skills**. **Looking back**, I also think that it **plays a role in** improving my **fine motor skills**, even though I **wasn't aware of it at the time**.
   Overall, it was **more than just** a toy. It was a gift that **stood the test of time**. And even now, it reminds me that simple, **hands-on toys** can be far more meaningful than expensive, **high-tech** ones.
