
## 1. To what extent do you agree or disagree?

### Partially agree / agree to a certain extent -> prefer by examiner

- like discuss both views
- **introduction**
  - Paraphrase the question
  - State that you're partially agree
- **1st body paragraph:**
  - Reasons agree
  - Explain + Example
- **2nd body paragraph:**
  - Reasons disagree
  - Explain + Example
- **conclusion:**
  - Restate balanced position

### Totally agree / Totally disagree

- At least 2 solid arguments, no counter argument needed
- **introduction**
  - Paraphrase the question
  - State that you're totally agree
- **1st body paragraph:**
  - First reason agree
- **2nd body paragraph:**
  - Second reason disagree
- **conclusion:**
  - Restate balanced position

### Mostly agree / disagree

- Like partially agree, but focus more on one view + 1 counter-argument in the second paragraph
- **introduction**
  - Paraphrase the question
  - State that you're partially agree
- **1st body paragraph:** Strong
  - Reasons to agree
- **2nd body paragraph:** Weak
  - Exception and Limitation
- **conclusion:**
  - Restate your position

### Commonly used phrases

## 2. Discuss both view and give your own opinion

### 1st approach

- **introduction**
  - Paraphrase the question
  - State that you will examine both views and argue that... (brief)
- **1st body paragraph:**
  - Reasons of one view (1 to 2 reasons)
- **2nd body paragraph:**
  - Reasons of other view
- **conclusion:**
  - Conclusion of 2 views + give your opinion (again, more clearly)

### 2nd approach

- introduction and conclusion are the same, but clearly state your opinion in the 2nd paragraph
- **1st body paragraph:**
  - Reasons of one view (usually the view that you **disagree**)
- **2nd body paragraph:**
  - Reasons of other view
  - Clearly state that **this is your opinion**

### Phrases for discuss both views

## 3. Do the advantages outweigh the disadvantages

- ...
- **introduction**
  - Paraphrase the question
  - State that you will examine the advantages and disadvantages to show that / and propose whether or not...
- **1st body paragraph:**
  - Advantages
- **2nd body paragraph:**
  - Disadvantages, 2 directions
    - Directly state the disadvantage
    - Admit the advantage, but practical application is not easy
- **conclusion:**
  - Conclusion of advantages and disadvantages + give your opinion (again, more clearly)

### Phrases for advantages and disadvantages

- there are some benefits associated with...
- this measure would have some problematic implications that should receive more attention

## 4. What are the Reasons? What are the Solutions?

- **introduction**
  - Paraphrase the question
  - State that you will examine the reasons and propose solutions for this problem
- **1st body paragraph:**
  - Reasons
- **2nd body paragraph:**
  - Solutions
- **conclusion:**
  - Brief conclusion of reasons + Brief conclusion of solutions
