
1. quay: cầu cảng
  - /kē/ - đọc như "key"
2. minute spacecraft
  - /maɪˈnuːt/
3. pray -> prayer
  - /prer/
4. Mitch's desk, everyone else's thing
  - EV-ree-wun ELS-**es**
5. extraordinary
  - /ekˈstrôrdnˌerē/
6. comfortable
7. debt
  - /det/ - silent "b"
8. often
  - /ˈɒfn/
9. subtle
  - /ˈsʌb.təl/
10. palm
  - /pɑːm/
11. live (trực tuyến)
  - /laɪv/
12. lead (n - kim loại)
  - /led/
13. colonel
  - /ˈkərn(ə)l/
14. choir
  - /ˈkwaɪər/
15. yacht
  - /yät/
16. height
  - /haɪt/
17. avantageous
  - /ˌadˌvanˈtājəs,ˌadvənˈtājəs/
