
- [Work - Study - Speaking Questions](work-study-speaking-questions)

## Study

1. challenging curriculum
  - The university has a **rigorous curriculum** that pushes students intellectually.
2. difficulty of learning
  - There was a **steep learning curve** in my first year.
3. kỹ năng suy luận, phân tích
  - Higher education should **foster** **critical thinking skills**.
4. học thuộc lòng
  - **Rote learning** causes students to pass the subject without real understanding of the materials.
5. learning independently
  - Universities should focus more on improving soft-skills. Among which are problem solving, time management and **self-directed learning**.
6. sự đánh giá liên tục
  - There are quizzes and small projects every week, so that grades are based on **continuous assessment** rather than final exams.
7. học tốt ; học tệ
  - Children who **excel academically** at an early age tend to have more pressure and emotional burden, which in turns makes them **underperform**.

## Work

1. triển vọng nghề nghiệp tốt
  - The role offers **strong long-term career prospects**.
2. sự thỏa mãn trong công việc
  - **Job satisfaction** matters more than salary to me.
3. cân bằng giữa cuộc sống và công việc
  - Poor **work-life balance** leads to **burnout**.
4. tăng kĩ năng :v
  - Workers must constantly **upskill** to remain competitive.
5. phân biệt giới tính ở nơi làm việc
  - **Job interviews** should be closely supervised and guided by transparent, **pre-established hiring criteria** to prevent **gender discrimination**, **harassment**, and **gatekeeping** against women during the **recruitment process.**
