
## 1. How to write a sentence

- start with year
- start with an element in the graph
- start with a modifier (a number of ...)

## 2. Structure of writing task 1

- Opening: question paraphrase, overview
- Main part: Explain the trend, focus on key features instead of overly explain everything
- Closing: conclusion
- [Vocabulary - Writing part 1](vocabulary-writing-part-1)

## 4. Các dạng đề cần review

- Có thời gian
- Không có thời gian
- Process
- Map

## 5. Tips

- Viết overview không được đưa vào thông tin chi tiết

## 6. My current weaknesses

- Check data accuracy when reporting
- Write a clearer, more specific overview
  - Structure: most popular overall -> biggest increase -> biggest decrease
- `timeframe from ... to ...` -> `timeframe between ... and ...`
- Use past simple, not past perfect
- `downfall in number` -> `decline in number`
- Should try paraphrasing more
  - people participated / joined ; participants -> attendance, enrollment, the figure stood at, the total rose to, the total climbed to
- Strategy: Each sentence has to be perfect, no time for a second check
