
1. a huge amount of
  1. an excessive number of ...
2. causes
  1. give rise to
  2. lead to
  3. result in
3. evidence
  1. ... is particularly evident when considering the fact that...: cái này có thể thấy rõ khi ta xem xét việc...
4. In long term,...
  1. From a long-term perspective,...
5. ... is an important cause of...
  1. play an important role in
  2. is a key contributing factor to
6. reduce
  - significantly / dramatically reduce
  - mitigate
  - alleviate
7. obviously
  - it is widely acknowledged that...
  - undeniably
8. solve the problem
  - address the root cause of the problem
9. make people angry
  - prompt backlashes / a backlash
  - public outrage
  - risk public backlash
10. recently
  - as of late
  - in recent years
  - over the past decade
11. nowadays
  - in modern / contemporary society
12. the use of sth
  - the adoption of sth
    - adoption of renewable energy / a healthy lifestyle
    - technology adoption; AI adoption
13. economic growth
  - economic expansion
  - economic productivity gain
14. people
  - supporter
  - advocate
  - proponents
15. an effective way / approach
  - a practical mean
  - an effective measure
  - solution
16. một thứ gì đó không nên được làm một mình mà phải có sự cân bằng (this should not be done...)
  - alone
  - in isolation
17. should
  - be obliged to...
18. argue
  - believe
  - contend

 19. achieve
   - attain (achievement, closer  to achieve)
   - obtain (object, data, permission)
 20. include / contain
   - encompass (include various things - "circle around" - course, plan, event)
   - incorporate (sth that has sth else built into - "carefully mix into" - design, advertisement, company, school curriculum,...)
   - feature (show off sth that is prominent - show, exhibition,...)
